camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  max-tasks: 1
  lock-duration: 20000
  worker-id: spring-boot-worker-1
  async-response-timeout: 2000
  disable-backoff-strategy: true
logging:
  level:
    "[org.apache.http]": INFO
